/* automatically generated by rust-bindgen 0.72.1 */

pub const MPV_ENABLE_DEPRECATED: u32 = 1;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::std::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::std::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_handle {
    _unused: [u8; 0],
}
#[doc = " No error happened (used to signal successful operation).\n Keep in mind that many API functions returning error codes can also\n return positive values, which also indicate success. API users can\n hardcode the fact that \">= 0\" means success."]
pub const mpv_error_MPV_ERROR_SUCCESS: mpv_error = 0;
#[doc = " The event ringbuffer is full. This means the client is choked, and can't\n receive any events. This can happen when too many asynchronous requests\n have been made, but not answered. Probably never happens in practice,\n unless the mpv core is frozen for some reason, and the client keeps\n making asynchronous requests. (Bugs in the client API implementation\n could also trigger this, e.g. if events become \"lost\".)"]
pub const mpv_error_MPV_ERROR_EVENT_QUEUE_FULL: mpv_error = -1;
#[doc = " Memory allocation failed."]
pub const mpv_error_MPV_ERROR_NOMEM: mpv_error = -2;
#[doc = " The mpv core wasn't configured and initialized yet. See the notes in\n mpv_create()."]
pub const mpv_error_MPV_ERROR_UNINITIALIZED: mpv_error = -3;
#[doc = " Generic catch-all error if a parameter is set to an invalid or\n unsupported value. This is used if there is no better error code."]
pub const mpv_error_MPV_ERROR_INVALID_PARAMETER: mpv_error = -4;
#[doc = " Trying to set an option that doesn't exist."]
pub const mpv_error_MPV_ERROR_OPTION_NOT_FOUND: mpv_error = -5;
#[doc = " Trying to set an option using an unsupported MPV_FORMAT."]
pub const mpv_error_MPV_ERROR_OPTION_FORMAT: mpv_error = -6;
#[doc = " Setting the option failed. Typically this happens if the provided option\n value could not be parsed."]
pub const mpv_error_MPV_ERROR_OPTION_ERROR: mpv_error = -7;
#[doc = " The accessed property doesn't exist."]
pub const mpv_error_MPV_ERROR_PROPERTY_NOT_FOUND: mpv_error = -8;
#[doc = " Trying to set or get a property using an unsupported MPV_FORMAT."]
pub const mpv_error_MPV_ERROR_PROPERTY_FORMAT: mpv_error = -9;
#[doc = " The property exists, but is not available. This usually happens when the\n associated subsystem is not active, e.g. querying audio parameters while\n audio is disabled."]
pub const mpv_error_MPV_ERROR_PROPERTY_UNAVAILABLE: mpv_error = -10;
#[doc = " Error setting or getting a property."]
pub const mpv_error_MPV_ERROR_PROPERTY_ERROR: mpv_error = -11;
#[doc = " General error when running a command with mpv_command and similar."]
pub const mpv_error_MPV_ERROR_COMMAND: mpv_error = -12;
#[doc = " Generic error on loading (usually used with mpv_event_end_file.error)."]
pub const mpv_error_MPV_ERROR_LOADING_FAILED: mpv_error = -13;
#[doc = " Initializing the audio output failed."]
pub const mpv_error_MPV_ERROR_AO_INIT_FAILED: mpv_error = -14;
#[doc = " Initializing the video output failed."]
pub const mpv_error_MPV_ERROR_VO_INIT_FAILED: mpv_error = -15;
#[doc = " There was no audio or video data to play. This also happens if the\n file was recognized, but did not contain any audio or video streams,\n or no streams were selected."]
pub const mpv_error_MPV_ERROR_NOTHING_TO_PLAY: mpv_error = -16;
#[doc = " When trying to load the file, the file format could not be determined,\n or the file was too broken to open it."]
pub const mpv_error_MPV_ERROR_UNKNOWN_FORMAT: mpv_error = -17;
#[doc = " Generic error for signaling that certain system requirements are not\n fulfilled."]
pub const mpv_error_MPV_ERROR_UNSUPPORTED: mpv_error = -18;
#[doc = " The API function which was called is a stub only."]
pub const mpv_error_MPV_ERROR_NOT_IMPLEMENTED: mpv_error = -19;
#[doc = " Unspecified error."]
pub const mpv_error_MPV_ERROR_GENERIC: mpv_error = -20;
#[doc = " List of error codes than can be returned by API functions. 0 and positive\n return values always mean success, negative values are always errors."]
pub type mpv_error = ::std::os::raw::c_int;
#[doc = " Invalid. Sometimes used for empty values. This is always defined to 0,\n so a normal 0-init of mpv_format (or e.g. mpv_node) is guaranteed to set\n this it to MPV_FORMAT_NONE (which makes some things saner as consequence)."]
pub const mpv_format_MPV_FORMAT_NONE: mpv_format = 0;
#[doc = " The basic type is char*. It returns the raw property string, like\n using ${=property} in input.conf (see input.rst).\n\n NULL isn't an allowed value.\n\n Warning: although the encoding is usually UTF-8, this is not always the\n          case. File tags often store strings in some legacy codepage,\n          and even filenames don't necessarily have to be in UTF-8 (at\n          least on Linux). If you pass the strings to code that requires\n          valid UTF-8, you have to sanitize it in some way.\n          On Windows, filenames are always UTF-8, and libmpv converts\n          between UTF-8 and UTF-16 when using win32 API functions. See\n          the \"Encoding of filenames\" section for details.\n\n Example for reading:\n\n     char *result = NULL;\n     if (mpv_get_property(ctx, \"property\", MPV_FORMAT_STRING, &result) < 0)\n         goto error;\n     printf(\"%s\\n\", result);\n     mpv_free(result);\n\n Or just use mpv_get_property_string().\n\n Example for writing:\n\n     char *value = \"the new value\";\n     // yep, you pass the address to the variable\n     // (needed for symmetry with other types and mpv_get_property)\n     mpv_set_property(ctx, \"property\", MPV_FORMAT_STRING, &value);\n\n Or just use mpv_set_property_string().\n"]
pub const mpv_format_MPV_FORMAT_STRING: mpv_format = 1;
#[doc = " The basic type is char*. It returns the OSD property string, like\n using ${property} in input.conf (see input.rst). In many cases, this\n is the same as the raw string, but in other cases it's formatted for\n display on OSD. It's intended to be human readable. Do not attempt to\n parse these strings.\n\n Only valid when doing read access. The rest works like MPV_FORMAT_STRING."]
pub const mpv_format_MPV_FORMAT_OSD_STRING: mpv_format = 2;
#[doc = " The basic type is int. The only allowed values are 0 (\"no\")\n and 1 (\"yes\").\n\n Example for reading:\n\n     int result;\n     if (mpv_get_property(ctx, \"property\", MPV_FORMAT_FLAG, &result) < 0)\n         goto error;\n     printf(\"%s\\n\", result ? \"true\" : \"false\");\n\n Example for writing:\n\n     int flag = 1;\n     mpv_set_property(ctx, \"property\", MPV_FORMAT_FLAG, &flag);"]
pub const mpv_format_MPV_FORMAT_FLAG: mpv_format = 3;
#[doc = " The basic type is int64_t."]
pub const mpv_format_MPV_FORMAT_INT64: mpv_format = 4;
#[doc = " The basic type is double."]
pub const mpv_format_MPV_FORMAT_DOUBLE: mpv_format = 5;
#[doc = " The type is mpv_node.\n\n For reading, you usually would pass a pointer to a stack-allocated\n mpv_node value to mpv, and when you're done you call\n mpv_free_node_contents(&node).\n You're expected not to write to the data - if you have to, copy it\n first (which you have to do manually).\n\n For writing, you construct your own mpv_node, and pass a pointer to the\n API. The API will never write to your data (and copy it if needed), so\n you're free to use any form of allocation or memory management you like.\n\n Warning: when reading, always check the mpv_node.format member. For\n          example, properties might change their type in future versions\n          of mpv, or sometimes even during runtime.\n\n Example for reading:\n\n     mpv_node result;\n     if (mpv_get_property(ctx, \"property\", MPV_FORMAT_NODE, &result) < 0)\n         goto error;\n     printf(\"format=%d\\n\", (int)result.format);\n     mpv_free_node_contents(&result).\n\n Example for writing:\n\n     mpv_node value;\n     value.format = MPV_FORMAT_STRING;\n     value.u.string = \"hello\";\n     mpv_set_property(ctx, \"property\", MPV_FORMAT_NODE, &value);"]
pub const mpv_format_MPV_FORMAT_NODE: mpv_format = 6;
#[doc = " Used with mpv_node only. Can usually not be used directly."]
pub const mpv_format_MPV_FORMAT_NODE_ARRAY: mpv_format = 7;
#[doc = " See MPV_FORMAT_NODE_ARRAY."]
pub const mpv_format_MPV_FORMAT_NODE_MAP: mpv_format = 8;
#[doc = " A raw, untyped byte array. Only used only with mpv_node, and only in\n some very specific situations. (Some commands use it.)"]
pub const mpv_format_MPV_FORMAT_BYTE_ARRAY: mpv_format = 9;
#[doc = " Data format for options and properties. The API functions to get/set\n properties and options support multiple formats, and this enum describes\n them."]
pub type mpv_format = ::std::os::raw::c_uint;
#[doc = " Generic data storage.\n\n If mpv writes this struct (e.g. via mpv_get_property()), you must not change\n the data. In some cases (mpv_get_property()), you have to free it with\n mpv_free_node_contents(). If you fill this struct yourself, you're also\n responsible for freeing it, and you must not call mpv_free_node_contents()."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mpv_node {
    pub u: mpv_node__bindgen_ty_1,
    #[doc = " Type of the data stored in this struct. This value rules what members in\n the given union can be accessed. The following formats are currently\n defined to be allowed in mpv_node:\n\n  MPV_FORMAT_STRING       (u.string)\n  MPV_FORMAT_FLAG         (u.flag)\n  MPV_FORMAT_INT64        (u.int64)\n  MPV_FORMAT_DOUBLE       (u.double_)\n  MPV_FORMAT_NODE_ARRAY   (u.list)\n  MPV_FORMAT_NODE_MAP     (u.list)\n  MPV_FORMAT_BYTE_ARRAY   (u.ba)\n  MPV_FORMAT_NONE         (no member)\n\n If you encounter a value you don't know, you must not make any\n assumptions about the contents of union u."]
    pub format: mpv_format,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union mpv_node__bindgen_ty_1 {
    pub string: *mut ::std::os::raw::c_char,
    #[doc = " valid if format==MPV_FORMAT_STRING"]
    pub flag: ::std::os::raw::c_int,
    #[doc = " valid if format==MPV_FORMAT_FLAG"]
    pub int64: i64,
    #[doc = " valid if format==MPV_FORMAT_INT64"]
    pub double_: f64,
    #[doc = " valid if format==MPV_FORMAT_DOUBLE */\n/**\n valid if format==MPV_FORMAT_NODE_ARRAY\n    or if format==MPV_FORMAT_NODE_MAP"]
    pub list: *mut mpv_node_list,
    #[doc = " valid if format==MPV_FORMAT_BYTE_ARRAY"]
    pub ba: *mut mpv_byte_array,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_node__bindgen_ty_1"][::std::mem::size_of::<mpv_node__bindgen_ty_1>() - 8usize];
    ["Alignment of mpv_node__bindgen_ty_1"][::std::mem::align_of::<mpv_node__bindgen_ty_1>() - 8usize];
    ["Offset of field: mpv_node__bindgen_ty_1::string"]
        [::std::mem::offset_of!(mpv_node__bindgen_ty_1, string) - 0usize];
    ["Offset of field: mpv_node__bindgen_ty_1::flag"][::std::mem::offset_of!(mpv_node__bindgen_ty_1, flag) - 0usize];
    ["Offset of field: mpv_node__bindgen_ty_1::int64"][::std::mem::offset_of!(mpv_node__bindgen_ty_1, int64) - 0usize];
    ["Offset of field: mpv_node__bindgen_ty_1::double_"]
        [::std::mem::offset_of!(mpv_node__bindgen_ty_1, double_) - 0usize];
    ["Offset of field: mpv_node__bindgen_ty_1::list"][::std::mem::offset_of!(mpv_node__bindgen_ty_1, list) - 0usize];
    ["Offset of field: mpv_node__bindgen_ty_1::ba"][::std::mem::offset_of!(mpv_node__bindgen_ty_1, ba) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_node"][::std::mem::size_of::<mpv_node>() - 16usize];
    ["Alignment of mpv_node"][::std::mem::align_of::<mpv_node>() - 8usize];
    ["Offset of field: mpv_node::u"][::std::mem::offset_of!(mpv_node, u) - 0usize];
    ["Offset of field: mpv_node::format"][::std::mem::offset_of!(mpv_node, format) - 8usize];
};
#[doc = " (see mpv_node)"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_node_list {
    #[doc = " Number of entries. Negative values are not allowed."]
    pub num: ::std::os::raw::c_int,
    #[doc = " MPV_FORMAT_NODE_ARRAY:\n  values[N] refers to value of the Nth item\n\n MPV_FORMAT_NODE_MAP:\n  values[N] refers to value of the Nth key/value pair\n\n If num > 0, values[0] to values[num-1] (inclusive) are valid.\n Otherwise, this can be NULL."]
    pub values: *mut mpv_node,
    #[doc = " MPV_FORMAT_NODE_ARRAY:\n  unused (typically NULL), access is not allowed\n\n MPV_FORMAT_NODE_MAP:\n  keys[N] refers to key of the Nth key/value pair. If num > 0, keys[0] to\n  keys[num-1] (inclusive) are valid. Otherwise, this can be NULL.\n  The keys are in random order. The only guarantee is that keys[N] belongs\n  to the value values[N]. NULL keys are not allowed."]
    pub keys: *mut *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_node_list"][::std::mem::size_of::<mpv_node_list>() - 24usize];
    ["Alignment of mpv_node_list"][::std::mem::align_of::<mpv_node_list>() - 8usize];
    ["Offset of field: mpv_node_list::num"][::std::mem::offset_of!(mpv_node_list, num) - 0usize];
    ["Offset of field: mpv_node_list::values"][::std::mem::offset_of!(mpv_node_list, values) - 8usize];
    ["Offset of field: mpv_node_list::keys"][::std::mem::offset_of!(mpv_node_list, keys) - 16usize];
};
#[doc = " (see mpv_node)"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_byte_array {
    #[doc = " Pointer to the data. In what format the data is stored is up to whatever\n uses MPV_FORMAT_BYTE_ARRAY."]
    pub data: *mut ::std::os::raw::c_void,
    #[doc = " Size of the data pointed to by ptr."]
    pub size: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_byte_array"][::std::mem::size_of::<mpv_byte_array>() - 16usize];
    ["Alignment of mpv_byte_array"][::std::mem::align_of::<mpv_byte_array>() - 8usize];
    ["Offset of field: mpv_byte_array::data"][::std::mem::offset_of!(mpv_byte_array, data) - 0usize];
    ["Offset of field: mpv_byte_array::size"][::std::mem::offset_of!(mpv_byte_array, size) - 8usize];
};
#[doc = " Nothing happened. Happens on timeouts or sporadic wakeups."]
pub const mpv_event_id_MPV_EVENT_NONE: mpv_event_id = 0;
#[doc = " Happens when the player quits. The player enters a state where it tries\n to disconnect all clients. Most requests to the player will fail, and\n the client should react to this and quit with mpv_destroy() as soon as\n possible."]
pub const mpv_event_id_MPV_EVENT_SHUTDOWN: mpv_event_id = 1;
#[doc = " See mpv_request_log_messages()."]
pub const mpv_event_id_MPV_EVENT_LOG_MESSAGE: mpv_event_id = 2;
#[doc = " Reply to a mpv_get_property_async() request.\n See also mpv_event and mpv_event_property."]
pub const mpv_event_id_MPV_EVENT_GET_PROPERTY_REPLY: mpv_event_id = 3;
#[doc = " Reply to a mpv_set_property_async() request.\n (Unlike MPV_EVENT_GET_PROPERTY, mpv_event_property is not used.)"]
pub const mpv_event_id_MPV_EVENT_SET_PROPERTY_REPLY: mpv_event_id = 4;
#[doc = " Reply to a mpv_command_async() or mpv_command_node_async() request.\n See also mpv_event and mpv_event_command."]
pub const mpv_event_id_MPV_EVENT_COMMAND_REPLY: mpv_event_id = 5;
#[doc = " Notification before playback start of a file (before the file is loaded).\n See also mpv_event and mpv_event_start_file."]
pub const mpv_event_id_MPV_EVENT_START_FILE: mpv_event_id = 6;
#[doc = " Notification after playback end (after the file was unloaded).\n See also mpv_event and mpv_event_end_file."]
pub const mpv_event_id_MPV_EVENT_END_FILE: mpv_event_id = 7;
#[doc = " Notification when the file has been loaded (headers were read etc.), and\n decoding starts."]
pub const mpv_event_id_MPV_EVENT_FILE_LOADED: mpv_event_id = 8;
#[doc = " Idle mode was entered. In this mode, no file is played, and the playback\n core waits for new commands. (The command line player normally quits\n instead of entering idle mode, unless --idle was specified. If mpv\n was started with mpv_create(), idle mode is enabled by default.)\n\n @deprecated This is equivalent to using mpv_observe_property() on the\n             \"idle-active\" property. The event is redundant, and might be\n             removed in the far future. As a further warning, this event\n             is not necessarily sent at the right point anymore (at the\n             start of the program), while the property behaves correctly."]
pub const mpv_event_id_MPV_EVENT_IDLE: mpv_event_id = 11;
#[doc = " Sent every time after a video frame is displayed. Note that currently,\n this will be sent in lower frequency if there is no video, or playback\n is paused - but that will be removed in the future, and it will be\n restricted to video frames only.\n\n @deprecated Use mpv_observe_property() with relevant properties instead\n             (such as \"playback-time\")."]
pub const mpv_event_id_MPV_EVENT_TICK: mpv_event_id = 14;
#[doc = " Triggered by the script-message input command. The command uses the\n first argument of the command as client name (see mpv_client_name()) to\n dispatch the message, and passes along all arguments starting from the\n second argument as strings.\n See also mpv_event and mpv_event_client_message."]
pub const mpv_event_id_MPV_EVENT_CLIENT_MESSAGE: mpv_event_id = 16;
#[doc = " Happens after video changed in some way. This can happen on resolution\n changes, pixel format changes, or video filter changes. The event is\n sent after the video filters and the VO are reconfigured. Applications\n embedding a mpv window should listen to this event in order to resize\n the window if needed.\n Note that this event can happen sporadically, and you should check\n yourself whether the video parameters really changed before doing\n something expensive."]
pub const mpv_event_id_MPV_EVENT_VIDEO_RECONFIG: mpv_event_id = 17;
#[doc = " Similar to MPV_EVENT_VIDEO_RECONFIG. This is relatively uninteresting,\n because there is no such thing as audio output embedding."]
pub const mpv_event_id_MPV_EVENT_AUDIO_RECONFIG: mpv_event_id = 18;
#[doc = " Happens when a seek was initiated. Playback stops. Usually it will\n resume with MPV_EVENT_PLAYBACK_RESTART as soon as the seek is finished."]
pub const mpv_event_id_MPV_EVENT_SEEK: mpv_event_id = 20;
#[doc = " There was a discontinuity of some sort (like a seek), and playback\n was reinitialized. Usually happens on start of playback and after\n seeking. The main purpose is allowing the client to detect when a seek\n request is finished."]
pub const mpv_event_id_MPV_EVENT_PLAYBACK_RESTART: mpv_event_id = 21;
#[doc = " Event sent due to mpv_observe_property().\n See also mpv_event and mpv_event_property."]
pub const mpv_event_id_MPV_EVENT_PROPERTY_CHANGE: mpv_event_id = 22;
#[doc = " Happens if the internal per-mpv_handle ringbuffer overflows, and at\n least 1 event had to be dropped. This can happen if the client doesn't\n read the event queue quickly enough with mpv_wait_event(), or if the\n client makes a very large number of asynchronous calls at once.\n\n Event delivery will continue normally once this event was returned\n (this forces the client to empty the queue completely)."]
pub const mpv_event_id_MPV_EVENT_QUEUE_OVERFLOW: mpv_event_id = 24;
#[doc = " Triggered if a hook handler was registered with mpv_hook_add(), and the\n hook is invoked. If you receive this, you must handle it, and continue\n the hook with mpv_hook_continue().\n See also mpv_event and mpv_event_hook."]
pub const mpv_event_id_MPV_EVENT_HOOK: mpv_event_id = 25;
pub type mpv_event_id = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_event_property {
    #[doc = " Name of the property."]
    pub name: *const ::std::os::raw::c_char,
    #[doc = " Format of the data field in the same struct. See enum mpv_format.\n This is always the same format as the requested format, except when\n the property could not be retrieved (unavailable, or an error happened),\n in which case the format is MPV_FORMAT_NONE."]
    pub format: mpv_format,
    #[doc = " Received property value. Depends on the format. This is like the\n pointer argument passed to mpv_get_property().\n\n For example, for MPV_FORMAT_STRING you get the string with:\n\n    char *value = *(char **)(event_property->data);\n\n Note that this is set to NULL if retrieving the property failed (the\n format will be MPV_FORMAT_NONE)."]
    pub data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_event_property"][::std::mem::size_of::<mpv_event_property>() - 24usize];
    ["Alignment of mpv_event_property"][::std::mem::align_of::<mpv_event_property>() - 8usize];
    ["Offset of field: mpv_event_property::name"][::std::mem::offset_of!(mpv_event_property, name) - 0usize];
    ["Offset of field: mpv_event_property::format"][::std::mem::offset_of!(mpv_event_property, format) - 8usize];
    ["Offset of field: mpv_event_property::data"][::std::mem::offset_of!(mpv_event_property, data) - 16usize];
};
pub const mpv_log_level_MPV_LOG_LEVEL_NONE: mpv_log_level = 0;
#[doc = " \"no\"    - disable absolutely all messages"]
pub const mpv_log_level_MPV_LOG_LEVEL_FATAL: mpv_log_level = 10;
#[doc = " \"fatal\" - critical/aborting errors"]
pub const mpv_log_level_MPV_LOG_LEVEL_ERROR: mpv_log_level = 20;
#[doc = " \"error\" - simple errors"]
pub const mpv_log_level_MPV_LOG_LEVEL_WARN: mpv_log_level = 30;
#[doc = " \"warn\"  - possible problems"]
pub const mpv_log_level_MPV_LOG_LEVEL_INFO: mpv_log_level = 40;
#[doc = " \"info\"  - informational message"]
pub const mpv_log_level_MPV_LOG_LEVEL_V: mpv_log_level = 50;
#[doc = " \"v\"     - noisy informational message"]
pub const mpv_log_level_MPV_LOG_LEVEL_DEBUG: mpv_log_level = 60;
#[doc = " \"debug\" - very noisy technical information"]
pub const mpv_log_level_MPV_LOG_LEVEL_TRACE: mpv_log_level = 70;
#[doc = " Numeric log levels. The lower the number, the more important the message is.\n MPV_LOG_LEVEL_NONE is never used when receiving messages. The string in\n the comment after the value is the name of the log level as used for the\n mpv_request_log_messages() function.\n Unused numeric values are unused, but reserved for future use."]
pub type mpv_log_level = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_event_log_message {
    #[doc = " The module prefix, identifies the sender of the message. As a special\n case, if the message buffer overflows, this will be set to the string\n \"overflow\" (which doesn't appear as prefix otherwise), and the text\n field will contain an informative message."]
    pub prefix: *const ::std::os::raw::c_char,
    #[doc = " The log level as string. See mpv_request_log_messages() for possible\n values. The level \"no\" is never used here."]
    pub level: *const ::std::os::raw::c_char,
    #[doc = " The log message. It consists of 1 line of text, and is terminated with\n a newline character. (Before API version 1.6, it could contain multiple\n or partial lines.)"]
    pub text: *const ::std::os::raw::c_char,
    #[doc = " The same contents as the level field, but as a numeric ID.\n Since API version 1.6."]
    pub log_level: mpv_log_level,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_event_log_message"][::std::mem::size_of::<mpv_event_log_message>() - 32usize];
    ["Alignment of mpv_event_log_message"][::std::mem::align_of::<mpv_event_log_message>() - 8usize];
    ["Offset of field: mpv_event_log_message::prefix"][::std::mem::offset_of!(mpv_event_log_message, prefix) - 0usize];
    ["Offset of field: mpv_event_log_message::level"][::std::mem::offset_of!(mpv_event_log_message, level) - 8usize];
    ["Offset of field: mpv_event_log_message::text"][::std::mem::offset_of!(mpv_event_log_message, text) - 16usize];
    ["Offset of field: mpv_event_log_message::log_level"]
        [::std::mem::offset_of!(mpv_event_log_message, log_level) - 24usize];
};
#[doc = " The end of file was reached. Sometimes this may also happen on\n incomplete or corrupted files, or if the network connection was\n interrupted when playing a remote file. It also happens if the\n playback range was restricted with --end or --frames or similar."]
pub const mpv_end_file_reason_MPV_END_FILE_REASON_EOF: mpv_end_file_reason = 0;
#[doc = " Playback was stopped by an external action (e.g. playlist controls)."]
pub const mpv_end_file_reason_MPV_END_FILE_REASON_STOP: mpv_end_file_reason = 2;
#[doc = " Playback was stopped by the quit command or player shutdown."]
pub const mpv_end_file_reason_MPV_END_FILE_REASON_QUIT: mpv_end_file_reason = 3;
#[doc = " Some kind of error happened that lead to playback abort. Does not\n necessarily happen on incomplete or broken files (in these cases, both\n MPV_END_FILE_REASON_ERROR or MPV_END_FILE_REASON_EOF are possible).\n\n mpv_event_end_file.error will be set."]
pub const mpv_end_file_reason_MPV_END_FILE_REASON_ERROR: mpv_end_file_reason = 4;
#[doc = " The file was a playlist or similar. When the playlist is read, its\n entries will be appended to the playlist after the entry of the current\n file, the entry of the current file is removed, and a MPV_EVENT_END_FILE\n event is sent with reason set to MPV_END_FILE_REASON_REDIRECT. Then\n playback continues with the playlist contents.\n Since API version 1.18."]
pub const mpv_end_file_reason_MPV_END_FILE_REASON_REDIRECT: mpv_end_file_reason = 5;
#[doc = " Since API version 1.9."]
pub type mpv_end_file_reason = ::std::os::raw::c_uint;
#[doc = " Since API version 1.108."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_event_start_file {
    #[doc = " Playlist entry ID of the file being loaded now."]
    pub playlist_entry_id: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_event_start_file"][::std::mem::size_of::<mpv_event_start_file>() - 8usize];
    ["Alignment of mpv_event_start_file"][::std::mem::align_of::<mpv_event_start_file>() - 8usize];
    ["Offset of field: mpv_event_start_file::playlist_entry_id"]
        [::std::mem::offset_of!(mpv_event_start_file, playlist_entry_id) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_event_end_file {
    #[doc = " Corresponds to the values in enum mpv_end_file_reason.\n\n Unknown values should be treated as unknown."]
    pub reason: mpv_end_file_reason,
    #[doc = " If reason==MPV_END_FILE_REASON_ERROR, this contains a mpv error code\n (one of MPV_ERROR_...) giving an approximate reason why playback\n failed. In other cases, this field is 0 (no error).\n Since API version 1.9."]
    pub error: ::std::os::raw::c_int,
    #[doc = " Playlist entry ID of the file that was being played or attempted to be\n played. This has the same value as the playlist_entry_id field in the\n corresponding mpv_event_start_file event.\n Since API version 1.108."]
    pub playlist_entry_id: i64,
    #[doc = " If loading ended, because the playlist entry to be played was for example\n a playlist, and the current playlist entry is replaced with a number of\n other entries. This may happen at least with MPV_END_FILE_REASON_REDIRECT\n (other event types may use this for similar but different purposes in the\n future). In this case, playlist_insert_id will be set to the playlist\n entry ID of the first inserted entry, and playlist_insert_num_entries to\n the total number of inserted playlist entries. Note this in this specific\n case, the ID of the last inserted entry is playlist_insert_id+num-1.\n Beware that depending on circumstances, you may observe the new playlist\n entries before seeing the event (e.g. reading the \"playlist\" property or\n getting a property change notification before receiving the event).\n Since API version 1.108."]
    pub playlist_insert_id: i64,
    #[doc = " See playlist_insert_id. Only non-0 if playlist_insert_id is valid. Never\n negative.\n Since API version 1.108."]
    pub playlist_insert_num_entries: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_event_end_file"][::std::mem::size_of::<mpv_event_end_file>() - 32usize];
    ["Alignment of mpv_event_end_file"][::std::mem::align_of::<mpv_event_end_file>() - 8usize];
    ["Offset of field: mpv_event_end_file::reason"][::std::mem::offset_of!(mpv_event_end_file, reason) - 0usize];
    ["Offset of field: mpv_event_end_file::error"][::std::mem::offset_of!(mpv_event_end_file, error) - 4usize];
    ["Offset of field: mpv_event_end_file::playlist_entry_id"]
        [::std::mem::offset_of!(mpv_event_end_file, playlist_entry_id) - 8usize];
    ["Offset of field: mpv_event_end_file::playlist_insert_id"]
        [::std::mem::offset_of!(mpv_event_end_file, playlist_insert_id) - 16usize];
    ["Offset of field: mpv_event_end_file::playlist_insert_num_entries"]
        [::std::mem::offset_of!(mpv_event_end_file, playlist_insert_num_entries) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_event_client_message {
    #[doc = " Arbitrary arguments chosen by the sender of the message. If num_args > 0,\n you can access args[0] through args[num_args - 1] (inclusive). What\n these arguments mean is up to the sender and receiver.\n None of the valid items are NULL."]
    pub num_args: ::std::os::raw::c_int,
    pub args: *mut *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_event_client_message"][::std::mem::size_of::<mpv_event_client_message>() - 16usize];
    ["Alignment of mpv_event_client_message"][::std::mem::align_of::<mpv_event_client_message>() - 8usize];
    ["Offset of field: mpv_event_client_message::num_args"]
        [::std::mem::offset_of!(mpv_event_client_message, num_args) - 0usize];
    ["Offset of field: mpv_event_client_message::args"]
        [::std::mem::offset_of!(mpv_event_client_message, args) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_event_hook {
    #[doc = " The hook name as passed to mpv_hook_add()."]
    pub name: *const ::std::os::raw::c_char,
    #[doc = " Internal ID that must be passed to mpv_hook_continue()."]
    pub id: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_event_hook"][::std::mem::size_of::<mpv_event_hook>() - 16usize];
    ["Alignment of mpv_event_hook"][::std::mem::align_of::<mpv_event_hook>() - 8usize];
    ["Offset of field: mpv_event_hook::name"][::std::mem::offset_of!(mpv_event_hook, name) - 0usize];
    ["Offset of field: mpv_event_hook::id"][::std::mem::offset_of!(mpv_event_hook, id) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct mpv_event_command {
    #[doc = " Result data of the command. Note that success/failure is signaled\n separately via mpv_event.error. This field is only for result data\n in case of success. Most commands leave it at MPV_FORMAT_NONE. Set\n to MPV_FORMAT_NONE on failure."]
    pub result: mpv_node,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_event_command"][::std::mem::size_of::<mpv_event_command>() - 16usize];
    ["Alignment of mpv_event_command"][::std::mem::align_of::<mpv_event_command>() - 8usize];
    ["Offset of field: mpv_event_command::result"][::std::mem::offset_of!(mpv_event_command, result) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_event {
    #[doc = " One of mpv_event. Keep in mind that later ABI compatible releases might\n add new event types. These should be ignored by the API user."]
    pub event_id: mpv_event_id,
    #[doc = " This is mainly used for events that are replies to (asynchronous)\n requests. It contains a status code, which is >= 0 on success, or < 0\n on error (a mpv_error value). Usually, this will be set if an\n asynchronous request fails.\n Used for:\n  MPV_EVENT_GET_PROPERTY_REPLY\n  MPV_EVENT_SET_PROPERTY_REPLY\n  MPV_EVENT_COMMAND_REPLY"]
    pub error: ::std::os::raw::c_int,
    #[doc = " If the event is in reply to a request (made with this API and this\n API handle), this is set to the reply_userdata parameter of the request\n call. Otherwise, this field is 0.\n Used for:\n  MPV_EVENT_GET_PROPERTY_REPLY\n  MPV_EVENT_SET_PROPERTY_REPLY\n  MPV_EVENT_COMMAND_REPLY\n  MPV_EVENT_PROPERTY_CHANGE\n  MPV_EVENT_HOOK"]
    pub reply_userdata: u64,
    #[doc = " The meaning and contents of the data member depend on the event_id:\n  MPV_EVENT_GET_PROPERTY_REPLY:     mpv_event_property*\n  MPV_EVENT_PROPERTY_CHANGE:        mpv_event_property*\n  MPV_EVENT_LOG_MESSAGE:            mpv_event_log_message*\n  MPV_EVENT_CLIENT_MESSAGE:         mpv_event_client_message*\n  MPV_EVENT_START_FILE:             mpv_event_start_file* (since v1.108)\n  MPV_EVENT_END_FILE:               mpv_event_end_file*\n  MPV_EVENT_HOOK:                   mpv_event_hook*\n  MPV_EVENT_COMMAND_REPLY*          mpv_event_command*\n  other: NULL\n\n Note: future enhancements might add new event structs for existing or new\n       event types."]
    pub data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mpv_event"][::std::mem::size_of::<mpv_event>() - 24usize];
    ["Alignment of mpv_event"][::std::mem::align_of::<mpv_event>() - 8usize];
    ["Offset of field: mpv_event::event_id"][::std::mem::offset_of!(mpv_event, event_id) - 0usize];
    ["Offset of field: mpv_event::error"][::std::mem::offset_of!(mpv_event, error) - 4usize];
    ["Offset of field: mpv_event::reply_userdata"][::std::mem::offset_of!(mpv_event, reply_userdata) - 8usize];
    ["Offset of field: mpv_event::data"][::std::mem::offset_of!(mpv_event, data) - 16usize];
};
unsafe extern "C" {
    pub static mut pfn_mpv_client_api_version: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_ulong>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_error_string:
        ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_free: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_client_name:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle) -> *const ::std::os::raw::c_char>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_client_id: ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle) -> i64>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_create: ::std::option::Option<unsafe extern "C" fn() -> *mut mpv_handle>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_initialize:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle) -> ::std::os::raw::c_int>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_destroy: ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle)>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_terminate_destroy: ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle)>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_create_client: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *const ::std::os::raw::c_char) -> *mut mpv_handle,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_create_weak_client: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *const ::std::os::raw::c_char) -> *mut mpv_handle,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_load_config_file: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_get_time_ns: ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle) -> i64>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_get_time_us: ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle) -> i64>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_free_node_contents: ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_node)>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_set_option: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: *const ::std::os::raw::c_char,
            arg3: mpv_format,
            arg4: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_set_option_string: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: *const ::std::os::raw::c_char,
            arg3: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_command: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *mut *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_command_node: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *mut mpv_node, arg3: *mut mpv_node) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_command_ret: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: *mut *const ::std::os::raw::c_char,
            arg3: *mut mpv_node,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_command_string: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_command_async: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: u64,
            arg3: *mut *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_command_node_async: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: u64, arg3: *mut mpv_node) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_abort_async_command:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: u64)>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_set_property: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: *const ::std::os::raw::c_char,
            arg3: mpv_format,
            arg4: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_set_property_string: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: *const ::std::os::raw::c_char,
            arg3: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_del_property: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_set_property_async: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: u64,
            arg3: *const ::std::os::raw::c_char,
            arg4: mpv_format,
            arg5: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_get_property: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: *const ::std::os::raw::c_char,
            arg3: mpv_format,
            arg4: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_get_property_string: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_get_property_osd_string: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_get_property_async: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: u64,
            arg3: *const ::std::os::raw::c_char,
            arg4: mpv_format,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_observe_property: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: u64,
            arg3: *const ::std::os::raw::c_char,
            arg4: mpv_format,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_unobserve_property:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: u64) -> ::std::os::raw::c_int>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_event_name:
        ::std::option::Option<unsafe extern "C" fn(arg1: mpv_event_id) -> *const ::std::os::raw::c_char>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_event_to_node:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_node, arg2: *mut mpv_event) -> ::std::os::raw::c_int>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_request_event: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: mpv_event_id,
            arg3: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_request_log_messages: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_wait_event:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: f64) -> *mut mpv_event>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_wakeup: ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle)>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_set_wakeup_callback: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
            arg3: *mut ::std::os::raw::c_void,
        ),
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_wait_async_requests: ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle)>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_hook_add: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut mpv_handle,
            arg2: u64,
            arg3: *const ::std::os::raw::c_char,
            arg4: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >;
}
unsafe extern "C" {
    pub static mut pfn_mpv_hook_continue:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle, arg2: u64) -> ::std::os::raw::c_int>;
}
unsafe extern "C" {
    pub static mut pfn_mpv_get_wakeup_pipe:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut mpv_handle) -> ::std::os::raw::c_int>;
}
